use axum::{
    Router,
    extract::DefaultBodyLimit,
    routing::{get, post},
};
use std::sync::Arc;

use crate::AppState;
use super::handlers;

pub fn build_terminal_app_routes() -> Router<Arc<AppState>> {
    Router::new()
        // Local PTY terminal
        .route("/api/apps/terminal/local-ws", get(handlers::terminal_ws))
        // SSH connections CRUD
        .route(
            "/api/apps/terminal/connections",
            get(handlers::list_ssh_terminals).post(handlers::create_ssh_terminal),
        )
        .route(
            "/api/apps/terminal/connections/ws",
            get(handlers::ssh_terminal_ws),
        )
        .route(
            "/api/apps/terminal/connections/{id}",
            get(handlers::get_ssh_terminal)
                .patch(handlers::update_ssh_terminal)
                .delete(handlers::delete_ssh_terminal),
        )
        .route(
            "/api/apps/terminal/connections/{id}/stats",
            get(handlers::ssh_terminal_stats),
        )
        .route(
            "/api/apps/terminal/connections/{id}/ls",
            get(handlers::ssh_terminal_ls),
        )
        .route(
            "/api/apps/terminal/connections/{id}/ps",
            get(handlers::ssh_terminal_ps),
        )
        .route(
            "/api/apps/terminal/connections/{id}/kill",
            post(handlers::ssh_terminal_kill),
        )
        .route(
            "/api/apps/terminal/connections/{id}/df",
            get(handlers::ssh_terminal_df),
        )
        .route(
            "/api/apps/terminal/connections/{id}/net",
            get(handlers::ssh_terminal_net),
        )
        .route(
            "/api/apps/terminal/connections/{id}/mkdir",
            post(handlers::ssh_terminal_mkdir),
        )
        .route(
            "/api/apps/terminal/connections/{id}/rm",
            post(handlers::ssh_terminal_rm),
        )
        .route(
            "/api/apps/terminal/connections/{id}/rename",
            post(handlers::ssh_terminal_rename),
        )
        .route(
            "/api/apps/terminal/connections/{id}/mv",
            post(handlers::ssh_terminal_mv),
        )
        .route(
            "/api/apps/terminal/connections/{id}/read-file",
            post(handlers::ssh_terminal_read_file),
        )
        .route(
            "/api/apps/terminal/connections/{id}/write-file",
            post(handlers::ssh_terminal_write_file),
        )
        .route(
            "/api/apps/terminal/connections/{id}/download",
            get(handlers::ssh_terminal_download),
        )
        .route(
            "/api/apps/terminal/connections/{id}/upload",
            post(handlers::ssh_terminal_upload).layer(DefaultBodyLimit::disable()),
        )
        .route(
            "/api/apps/terminal/connections/{id}/docker/ps",
            get(handlers::ssh_docker_ps),
        )
        .route(
            "/api/apps/terminal/connections/{id}/docker/start",
            post(handlers::ssh_docker_start),
        )
        .route(
            "/api/apps/terminal/connections/{id}/docker/stop",
            post(handlers::ssh_docker_stop),
        )
        .route(
            "/api/apps/terminal/connections/{id}/docker/restart",
            post(handlers::ssh_docker_restart),
        )
        .route(
            "/api/apps/terminal/connections/{id}/docker/logs",
            post(handlers::ssh_docker_logs),
        )
        .route(
            "/api/apps/terminal/connections/{id}/docker/images",
            get(handlers::ssh_docker_images),
        )
        .route(
            "/api/apps/terminal/connections/{id}/docker/rm",
            post(handlers::ssh_docker_rm),
        )
        .route(
            "/api/apps/terminal/connections/{id}/docker/pause",
            post(handlers::ssh_docker_pause),
        )
        .route(
            "/api/apps/terminal/connections/{id}/docker/unpause",
            post(handlers::ssh_docker_unpause),
        )
        .route(
            "/api/apps/terminal/connections/{id}/docker/rmi",
            post(handlers::ssh_docker_rmi),
        )
        .route(
            "/api/apps/terminal/connections/{id}/docker/networks",
            get(handlers::ssh_docker_networks),
        )
        .route(
            "/api/apps/terminal/connections/{id}/docker/inspect",
            get(handlers::ssh_docker_inspect),
        )
        .route(
            "/api/apps/terminal/connections/{id}/docker/volumes",
            get(handlers::ssh_docker_volumes),
        )
        .route(
            "/api/apps/terminal/connections/{id}/docker/volume-rm",
            post(handlers::ssh_docker_volume_rm),
        )
        .route(
            "/api/apps/terminal/connections/{id}/docker/stats",
            get(handlers::ssh_docker_stats),
        )
        .route(
            "/api/apps/terminal/connections/{id}/docker/network-rm",
            post(handlers::ssh_docker_network_rm),
        )
        .route(
            "/api/apps/terminal/connections/{id}/docker/prune-images",
            post(handlers::ssh_docker_prune_images),
        )
        .route(
            "/api/apps/terminal/connections/{id}/docker/prune-volumes",
            post(handlers::ssh_docker_prune_volumes),
        )
        .route(
            "/api/apps/terminal/connections/{id}/docker/prune-networks",
            post(handlers::ssh_docker_prune_networks),
        )
        .route(
            "/api/apps/terminal/connections/{id}/docker/prune-system",
            post(handlers::ssh_docker_prune_system),
        )
}
