use axum::{
    routing::{delete, get, patch, post},
    Router,
};
use std::sync::Arc;

use crate::handlers::ssh_terminal;
use crate::AppState;

pub fn build_ssh_terminal_routes() -> Router<Arc<AppState>> {
    Router::new()
        .route("/api/ssh-terminals", get(ssh_terminal::list_ssh_terminals))
        .route(
            "/api/ssh-terminals",
            post(ssh_terminal::create_ssh_terminal),
        )
        .route(
            "/api/ssh-terminals/{id}",
            get(ssh_terminal::get_ssh_terminal),
        )
        .route(
            "/api/ssh-terminals/{id}",
            patch(ssh_terminal::update_ssh_terminal),
        )
        .route(
            "/api/ssh-terminals/{id}",
            delete(ssh_terminal::delete_ssh_terminal),
        )
        .route(
            "/api/ssh-terminals/{id}/stats",
            get(ssh_terminal::ssh_terminal_stats),
        )
        .route(
            "/api/ssh-terminals/{id}/ls",
            get(ssh_terminal::ssh_terminal_ls),
        )
        .route(
            "/api/ssh-terminals/{id}/ps",
            get(ssh_terminal::ssh_terminal_ps),
        )
        .route(
            "/api/ssh-terminals/{id}/kill",
            post(ssh_terminal::ssh_terminal_kill),
        )
        .route(
            "/api/ssh-terminals/{id}/df",
            get(ssh_terminal::ssh_terminal_df),
        )
        .route(
            "/api/ssh-terminals/{id}/net",
            get(ssh_terminal::ssh_terminal_net),
        )
        .route(
            "/api/ssh-terminals/{id}/mkdir",
            post(ssh_terminal::ssh_terminal_mkdir),
        )
        .route(
            "/api/ssh-terminals/{id}/rm",
            post(ssh_terminal::ssh_terminal_rm),
        )
        .route(
            "/api/ssh-terminals/{id}/rename",
            post(ssh_terminal::ssh_terminal_rename),
        )
        .route(
            "/api/ssh-terminals/{id}/read-file",
            post(ssh_terminal::ssh_terminal_read_file),
        )
        .route(
            "/api/ssh-terminals/{id}/write-file",
            post(ssh_terminal::ssh_terminal_write_file),
        )
        .route(
            "/api/ssh-terminals/{id}/download",
            get(ssh_terminal::ssh_terminal_download),
        )
        .route(
            "/api/ssh-terminals/{id}/docker/ps",
            get(ssh_terminal::ssh_docker_ps),
        )
        .route(
            "/api/ssh-terminals/{id}/docker/start",
            post(ssh_terminal::ssh_docker_start),
        )
        .route(
            "/api/ssh-terminals/{id}/docker/stop",
            post(ssh_terminal::ssh_docker_stop),
        )
        .route(
            "/api/ssh-terminals/{id}/docker/restart",
            post(ssh_terminal::ssh_docker_restart),
        )
        .route(
            "/api/ssh-terminals/{id}/docker/logs",
            post(ssh_terminal::ssh_docker_logs),
        )
        .route(
            "/api/ssh-terminals/{id}/docker/images",
            get(ssh_terminal::ssh_docker_images),
        )
        .route(
            "/api/ssh-terminals/{id}/docker/rm",
            post(ssh_terminal::ssh_docker_rm),
        )
        .route(
            "/api/ssh-terminals/{id}/docker/pause",
            post(ssh_terminal::ssh_docker_pause),
        )
        .route(
            "/api/ssh-terminals/{id}/docker/unpause",
            post(ssh_terminal::ssh_docker_unpause),
        )
        .route(
            "/api/ssh-terminals/{id}/docker/rmi",
            post(ssh_terminal::ssh_docker_rmi),
        )
        .route(
            "/api/ssh-terminals/{id}/docker/networks",
            get(ssh_terminal::ssh_docker_networks),
        )
        .route(
            "/api/ssh-terminals/{id}/docker/inspect",
            get(ssh_terminal::ssh_docker_inspect),
        )
        .route(
            "/api/ssh-terminals/{id}/docker/volumes",
            get(ssh_terminal::ssh_docker_volumes),
        )
        .route(
            "/api/ssh-terminals/{id}/docker/volume-rm",
            post(ssh_terminal::ssh_docker_volume_rm),
        )
        .route(
            "/api/ssh-terminals/{id}/docker/stats",
            get(ssh_terminal::ssh_docker_stats),
        )
        .route(
            "/api/ssh-terminals/{id}/docker/network-rm",
            post(ssh_terminal::ssh_docker_network_rm),
        )
        .route(
            "/api/ssh-terminals/{id}/docker/prune-images",
            post(ssh_terminal::ssh_docker_prune_images),
        )
        .route(
            "/api/ssh-terminals/{id}/docker/prune-volumes",
            post(ssh_terminal::ssh_docker_prune_volumes),
        )
        .route(
            "/api/ssh-terminals/{id}/docker/prune-networks",
            post(ssh_terminal::ssh_docker_prune_networks),
        )
        .route(
            "/api/ssh-terminals/{id}/docker/prune-system",
            post(ssh_terminal::ssh_docker_prune_system),
        )
        .route("/api/ssh-terminals/ws", get(ssh_terminal::ssh_terminal_ws))
}
