//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ssh_terminals")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub library_id: Uuid,
    pub file_system_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub host: String,
    pub port: i32,
    #[sea_orm(column_type = "Text")]
    pub username: String,
    #[sea_orm(column_type = "Text")]
    pub auth_method: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub password: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub private_key: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub passphrase: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub startup_command: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub sort_order: i32,
    pub is_enabled: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::file_systems::Entity",
        from = "Column::FileSystemId",
        to = "super::file_systems::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    FileSystems,
    #[sea_orm(
        belongs_to = "super::media_libraries::Entity",
        from = "Column::LibraryId",
        to = "super::media_libraries::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    MediaLibraries,
}

impl Related<super::file_systems::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileSystems.def()
    }
}

impl Related<super::media_libraries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaLibraries.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
